name: Check Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Block non-dev merges to main
        if: ${{ github.event.pull_request.base.ref == 'main'
          && github.event.pull_request.head.ref != 'dev'
          && !contains(github.event.pull_request.head.ref, 'po-deliverables') }}
        run: |
          echo "ERROR: You can only merge to main from dev or branches containing 'po-deliverables'."
          exit 1
